### ISSUE TITLE
Handling case sensitivity

### ISSUE THREAD

**Issue by stevector** [lcache/lcache#42]
Over in the Drupal 8 tests I'm getting a fail on case sensitivity: http://cgit.drupalcode.org/drupal/tree/core/modules/system/src/Tests/Cache/GenericCacheBackendUnitTestBase.php?h=8.2.0-rc2#n214

I'm running the test on a MySQL backend, different from the SQLite backend used in the tests for this library.

I can fix the MySQL test by changing [`WHERE "address" = :address`](https://github.com/lcache/lcache/blob/master/src/DatabaseL2.php#L153) to `WHERE BINARY "address" = :address`. However, doing so breaks SQLite which is case sensitive by default.

@davidstrauss, do you have thoughts on how best to proceed?

**Comment by davidstrauss** [comment]
The LCache library does not configure the schema, so this needs to be handled in the Drupal module. Specifically, the index should not be case-insensitive.

**Comment by davidstrauss** [comment]
I've posted [an issue on Drupal.org](https://www.drupal.org/node/2814939) for it, partly so it's visible to prospective users.
