### ISSUE TITLE
Remove redundant "LCache" prefix from classes in the LCache namespace

### ISSUE THREAD

**Issue by davidstrauss** [lcache/lcache#8]

**Comment by greg-1-anderson** [comment]
So, instead of:

LCache\LCache\LCacheL1 and LCache\LCache\LCacheX

You would prefer:

LCache\LCache\L1 and LCache\LCache\X

Correct?

Also, it is traditional to use org/project for namespaces, but since these are the same, we could drop one and just use:

LCache\L1 and LCache\X

**Comment by davidstrauss** [comment]
The only exception is that I would go LCacheX to LX.
