### ISSUE TITLE
Disable comments on PRs from Coveralls tool.

### ISSUE THREAD

**Issue by ndobromirov** [lcache/lcache#82]
### Steps to reproduce
Working on a PR. For example check #79.

### Expected behavior
To see only relevant stuff in the page.

### Actual behavior
There are 3 tools enabled at the time of writing . All of them validate the quality of the submitted code. But only 1 of them is spamming with comments in the thread (coveralls).

The report in the bottom is plenty of a status data and there are links to see details if something fails. 
So to my point, is there a way to silence it (configuration or something)?

### Frameworks tested
Which module / plugin were you using?
- [ ] Other (contributing to GITHIB's repo for LCache)

**Comment by davidstrauss** [comment]
I don't maintain the Coveralls configuration, but I've let others on the team here know.

**Comment by greg-1-anderson** [comment]
Done. Coveralls won't leave comments on PRs any longer.
