### ISSUE TITLE
Benchmark Scripts

### ISSUE THREAD

**Issue by ElijahLynn** [lcache/lcache#87]
I see some benchmark results here, https://docs.google.com/spreadsheets/d/1Jq0dyq76KWwmhlfUxlmnA6cMoWS6vfiBOKwZYlkbQ2Y/edit#gid=0, which are very useful. Can you share the benchmark script/testing methodology for this so we can run these benchmark tests too? If so, it might me useful to include in the repo itself. Maybe a BENCHMARK.md as well. 

p.s. Crossposted here https://www.drupal.org/project/lcache/issues/2957133

### Frameworks tested
Which module / plugin were you using?
- [ ] Drupal 8
- [x] Drupal 7
- [ ] WordPress
- [ ] Using lcache/lcache directly
- [ ] Other (specify)

**Comment by ElijahLynn** [comment]
Hrm, nice, I think I found them here. 

https://github.com/lcache/benchmarking

**Comment by davidstrauss** [comment]
Yep, you found them! If you're curious about making more use of LCache, it probably needs an L1 based on Redis or Memcached before handing serious, sustained use. This is primarily due to limitations in APCu.

**Comment by ElijahLynn** [comment]
Thanks for that guidance. For clarification, are you saying we shouldn't use just MariaDB plus LCache?

The goal of us using LCache would be to ditch our Memcached, since when one goes offline, it causes cache hangups due to the pool not being up to date.

**Comment by ElijahLynn** [comment]
For others who find this, I also found https://github.com/lcache/php-uc/blob/master/benchmark.php

**Comment by ElijahLynn** [comment]
Okay, so after processing more information, it sounds like the recommendation is to still use Memcached as the L1 cache since APCu has some limitations. Memcached doesn't need to be in a clustered mode and if that particular node failed it would not affect the whole cluster, because there would be no memcached cluster in this implementation.

The L1 cache would simply check memcache for a hit, and if it was missed then it would move to L2's DB cache. 

Is that a correct assumption?

**Comment by davidstrauss** [comment]
> For clarification, are you saying we shouldn't use just MariaDB plus LCache?

LCache requires two persistence stores: one that's central (MariaDB/MySQL) and one that's local to each PHP-FPM pool. Using APCu for the latter reveals performance bugs in APCu that are hard to fix. That's why I embarked on writing UC, but I shelved it as performance started converging on using something like memcached over a Unix socket.

**Comment by davidstrauss** [comment]
> The L1 cache would simply check memcache for a hit, and if it was missed then it would move to L2's DB cache. Is that a correct assumption?

It's correct, but it's probably worth stating that the L1 should be machine-local (and probably container-local) to each PHP-FPM pool. Almost all of the complexity in LCache is around managing the coherency of these machine-local caches so that cache hits don't require network traffic.

Also, the memcached L1 isn't implemented. It's probably the first thing I'd do if I picked this project up again. I'd be happy to take pull requests, though.

**Comment by ElijahLynn** [comment]
Okay, so in this implementation we would not be using APCu at all correct? The reason I ask is because all the documentation still says APCu. If we choose to use a socket to memcached, is that something that needs to be configured and is there any documentation on doing that? Or is this something that still needs to be documented?

**Comment by ElijahLynn** [comment]
Also, our stack is using mod_php MPM prefork. We have a move to php-fpm on our roadmap, but are currently trying to deal with memcache nodes going down affecting the whole cluster first.

**Comment by ElijahLynn** [comment]
Looks like only PHP-FPM is supported, "but the pool only tracks which PHP-FPM pool originated the event". 

source: https://github.com/lcache/lcache/issues/43#issuecomment-271738441

**Comment by davidstrauss** [comment]
> Okay, so in this implementation we would not be using APCu at all correct?

We would not be using APCu for any major storage. It may still make sense to track some counters and small values there (for performance reasons).

> The reason I ask is because all the documentation still says APCu.

The documentation reflects the state of the implementation, which still lacks a better L1 implementation.

> If we choose to use a socket to memcached, is that something that needs to be configured and is there any documentation on doing that?

The Unix socket would only be for performance reasons. TCP-based access would surely work fine as well, just slower. However, here's [a nice guide](https://guides.wp-bullet.com/configure-memcached-to-use-unix-socket-speed-boost/) for using PHP with memcached over a Unix socket.

> Or is this something that still needs to be documented?

Ideally, it would get documented after implementation.

**Comment by ElijahLynn** [comment]
Ah, thanks, I was misreading this as being roughly implemented now. Thanks for your time answering my questions. We can close this now.
